# Generated by Django 6.0.1 on 2026-04-07 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='job_description',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='ApplicationAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_title_guess', models.CharField(blank=True, max_length=200)),
                ('seniority_level', models.CharField(blank=True, max_length=100)),
                ('match_score', models.PositiveIntegerField(default=0)),
                ('fit_assessment', models.TextField(blank=True)),
                ('required_skills', models.JSONField(blank=True, default=list)),
                ('preferred_skills', models.JSONField(blank=True, default=list)),
                ('resume_strengths', models.JSONField(blank=True, default=list)),
                ('missing_or_weak_skills', models.JSONField(blank=True, default=list)),
                ('tailored_resume_suggestions', models.JSONField(blank=True, default=list)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='applications.application')),
            ],
        ),
    ]
